spring.application.name=categorization-service

spring.data.mongodb.uri=${MONGO_URI}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}